# Generated by Django 3.1.7 on 2021-03-29 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lottery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lotteryuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='lotteryrecord',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.lotteryactivity', verbose_name='活动'),
        ),
        migrations.AddField(
            model_name='lotteryrecord',
            name='prize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.prize', verbose_name='奖品'),
        ),
        migrations.AddField(
            model_name='lotteryrecord',
            name='user',
            field=models.ForeignKey(help_text='中奖人员', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
